#ifndef _TURINGWATCHER_SQL_SQL_H
#define _TURINGWATCHER_SQL_SQL_H
#include <cstdint>
#define DECLSQL(NAME) extern const char *NAME;
#define DB_SCHEMA_VERSION 1
constexpr uint32_t schema_version = DB_SCHEMA_VERSION;
DECLSQL(INIT_DB_SQL);
DECLSQL(UPSERT_WATCHER_SQL_RETURNING_TIMESTAMP_RANGE);
DECLSQL(REGISTER_WATCHER_SQL_RETURNING_TIMESTAMPS_AND_WATCHERID);
DECLSQL(JOBINFO_INSERT_SQL);
DECLSQL(GPU_MEASUREMENT_INSERT_SQL);
DECLSQL(GET_SCHEMA_VERSION_SQL);
DECLSQL(UPDATE_GPU_BATCH_SQL);
DECLSQL(MEASUREMENTS_INSERT_SQL);
DECLSQL(APPLICATION_USAGE_INSERT_SQL);
#undef DECLSQL
#endif
