#ifndef _TURINGWATCHER_SQL_SQL_H
#define _TURINGWATCHER_SQL_SQL_H
#define DECLSQL(NAME) extern const char *NAME;
DECLSQL(INIT_DB_SQL);
DECLSQL(UPSERT_WATCHER_SQL_RETURNING_TIMESTAMP_RANGE);
DECLSQL(REGISTER_WATCHER_SQL_RETURNING_TIMESTAMPS_AND_WATCHERID);
DECLSQL(JOBINFO_INSERT_SQL);
DECLSQL(MEASUREMENTS_INSERT_SQL);
#undef DECLSQL
#endif
